-- 移除 Issue→CycleEpic，删除 Epic 表；迭代增加类型与日程、项目文档字段
ALTER TABLE "Issue" DROP CONSTRAINT IF EXISTS "Issue_cycleEpicId_fkey";
ALTER TABLE "Issue" DROP COLUMN IF EXISTS "cycleEpicId";

DROP TABLE IF EXISTS "CycleEpic";

ALTER TABLE "Cycle" ADD COLUMN IF NOT EXISTS "kind" TEXT NOT NULL DEFAULT 'daily';
ALTER TABLE "Cycle" ADD COLUMN IF NOT EXISTS "plannedTestAt" TIMESTAMP(3);
ALTER TABLE "Cycle" ADD COLUMN IF NOT EXISTS "releaseAt" TIMESTAMP(3);
ALTER TABLE "Cycle" ADD COLUMN IF NOT EXISTS "productDocUrl" TEXT;
ALTER TABLE "Cycle" ADD COLUMN IF NOT EXISTS "designDocUrl" TEXT;
ALTER TABLE "Cycle" ADD COLUMN IF NOT EXISTS "uiDocUrl" TEXT;
